server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/himanshu?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&nullNamePatternMatchesAll=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&requireSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

management:
  endpoint:
    health:
      enabled: true
      show-details: "always"
  endpoints:
    web:
      exposure:
        include: "*"